version: '3.7'
services:
  graphapi:
    build: ./ 
    ports:
      - 8000:8000
    environment:
      - PG_HOST=pgdb
      - PG_DATABASE=postgres
      - PG_USER=postgres
      - PG_PASSWORD=postgres 
      - PG_PORT=5432
      - DATABASE_URL=postgresql://postgres:postgres@pgdb:5432/postgres
  
  pgdb:
    image: postgres:13-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres

volumes:
    postgres_data: